addons:
  sonarcloud:
    organization: "defra"

language: java

jdk:
  - openjdk8

# Travis CI uses shallow clone to speed up build times, but a truncated SCM
# history may cause issues when SonarCloud computes blame data. To avoid this,
# you can access the full SCM history with `depth: false`
git:
  depth: false

env:
  global:
    - WCRS_TEST_REGSDB_URI="mongodb://mongoUser:password1234@localhost:27017/waste-carriers-test"
    - WCRS_TEST_USERSDB_URI="mongodb://mongoUser:password1234@localhost:27017/waste-carriers-users-test"
    - WCRS_TEST_MONGODB_SERVER_SEL_TIMEOUT=1000

services:
  - mongodb

before_script:
  # Set up Mongo databases
  - mongo waste-carriers-test --eval 'db.createUser({user:"mongoUser", pwd:"password1234", roles:["readWrite", "dbAdmin", "userAdmin"]})'
  - mongo waste-carriers-users-test --eval 'db.createUser({user:"mongoUser", pwd:"password1234", roles:["readWrite", "dbAdmin", "userAdmin"]})'

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - ./mvnw clean test org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=DEFRA_waste-carriers-service
