# Default parameters defined in WasteCarrierConfiguration
template: Hello, %s, %s!
defaultName: Stranger

# messageQueue complex parameter to show class of different configuration types MessageQueueConfiguration
messageQueue:
  host: WESERVICES_MQ_HOST
  port: WESERVICES_MQ_PORT

# Added standard logging information
logging:
  # ...
  # Settings for logging to stdout.
  console:

    # If true, write log statements to stdout.
    enabled: true

    # Do not display log statements below this threshold to stdout.
    threshold: ALL

# added database connection properties, DatabaseConfiguration
database:
  host: WESERVICES_DB_HOST
  port: WESERVICES_DB_PORT
  name: WESERVICES_DB_NAME
  username: WESERVICES_DB_USER
  password: WESERVICES_DB_PASSWD

http:
  # The port on which the HTTP server listens for service requests.
  # Because Java cannot drop privileges in a POSIX system, these
  # ports cannot be in the range 1-1024. A port value of 0 will
  # make the OS use an arbitrary unused port.
  port: 9090
  
  # The port on which the HTTP server listens for administrative
  # requests. Subject to the same limitations as "port". If this is
  # set to the same value as port, the admin routes will be mounted
  # under /admin.
  adminPort: 9091
  
# more properties go here