# Default parameters defined in WasteCarrierConfiguration
template: Hello, %s, %s!
defaultName: Stranger

# messageQueue complex parameter to show class of different configuration types MessageQueueConfiguration
messageQueue:
  host: WESERVICESMQ_HOST
  port: WESERVICESMQ_PORT

# Added standard logging information
logging:
  # ...
  # Settings for logging to stdout.
  console:

    # If true, write log statements to stdout.
    enabled: true

    # Do not display log statements below this threshold to stdout.
    threshold: ALL

# added database connection properties, DatabaseConfiguration
database:
  host: WESERVICESDB_HOST
  port: WESERVICESDB_PORT
  name: WESERVICESDB_NAME
  username: WESERVICESDB_USER
  password: WESERVICESDB_PASSWD
  
# more properties go here
