# Default parameters defined in WasteCarrierConfiguration
template: Hello, %s, %s!
defaultName: Stranger

# messageQueue complex parameter to show class of different configuration types MessageQueueConfiguration
messageQueue:
  host: WCRS_SERVICES_MQ_HOST
  port: WCRS_SERVICES_MQ_PORT

# Added standard logging information
logging:
  # ...

  #standard logging level (should usually be INFO)
  level: INFO
  
  #Redefining logging levels for selected classes and packages
  loggers:
    "org.elasticsearch.client.transport": TRACE

  # Settings for logging to stdout.
  console:

    # If true, write log statements to stdout.
    enabled: true

    # Do not display log statements below this threshold to stdout.
    threshold: ALL

# added database connection properties, DatabaseConfiguration
database:
  host: WCRS_SERVICES_DB_HOST
  port: WCRS_SERVICES_DB_PORT
  name: WCRS_SERVICES_DB_NAME
  username: WCRS_SERVICES_DB_USER
  password: WCRS_SERVICES_DB_PASSWD
  
elasticSearch:
  host: WCRS_SERVICES_ES_HOST
  port: WCRS_SERVICES_ES_PORT
  # Can also specify a size for the maximum number of results to return in a given query
  # By default the 100 is used, but can be overridden here if specified
  #size: 100

http:
  # The port on which the HTTP server listens for service requests.
  # Because Java cannot drop privileges in a POSIX system, these
  # ports cannot be in the range 1-1024. A port value of 0 will
  # make the OS use an arbitrary unused port.
  port: WCRS_SERVICES_PORT
  
  # The port on which the HTTP server listens for administrative
  # requests. Subject to the same limitations as "port". If this is
  # set to the same value as port, the admin routes will be mounted
  # under /admin.
  adminPort: WCRS_SERVICES_ADMIN_PORT
  
settings:
  # registration period
  registrationPeriod: WCRS_FRONTEND_EXPIRES_AFTER
  # renew period
  registrationRenewPeriod: WCRS_FRONTEND_RENEWAL_WINDOW
  
# more properties go here
