# Default parameters defined in WasteCarrierConfiguration
template: Hello, %s, %s!
defaultName: Stranger

# messageQueue complex parameter to show class of different configuration types MessageQueueConfiguration
messageQueue:
  host: WESERVICES_MQ_HOST
  port: WESERVICES_MQ_PORT

# Added standard logging information
logging:
  # ...
  # Settings for logging to stdout.
  console:

    # If true, write log statements to stdout.
    enabled: true

    # Do not display log statements below this threshold to stdout.
    threshold: ALL

# added database connection properties, DatabaseConfiguration
database:
  host: WESERVICES_DB_HOST
  port: WESERVICES_DB_PORT
  name: WESERVICES_DB_NAME
  username: WESERVICES_DB_USER
  password: WESERVICES_DB_PASSWD
  
# more properties go here
