# Default parameters defined in WasteCarrierConfiguration
# http://www.dropwizard.io/1.3.1/docs/manual/configuration.html#man-configuration

# Added standard logging information
logging:
  #standard logging level (should usually be INFO)
  level: INFO
  appenders:
    # Settings for logging to stdout.
    - type: console
      # The lowest level of events to print to the console.
      threshold: ALL
      # The time zone to which event timestamps will be converted.
      timeZone: UTC
    # Setting for logging to file
    - type: file
      # The filename where current events are logged.
      currentLogFilename: ${WCRS_SERVICES_LOGFILE:-/srv/java/waste-carriers-service/logs/run.log}
      # The filename pattern for archived files. If the pattern ends with
      # .gz or .zip, files will be compressed as they are archived.
      archivedLogFilenamePattern: ${WCRS_SERVICES_LOGFILE_PATTERN:-/srv/java/waste-carriers-service/logs/run-archive-%d.log.gz}
      # The number of archived files to keep.
      archivedFileCount: 5
      # The time zone to which event timestamps will be converted.
      timeZone: UTC

server:
  # The port on which the HTTP server listens for service requests.
  # Because Java cannot drop privileges in a POSIX system, these
  # ports cannot be in the range 1-1024. A port value of 0 will
  # make the OS use an arbitrary unused port.
  applicationConnectors:
    - type: http
      port: 8004
  # The port on which the HTTP server listens for administrative
  # requests. Subject to the same limitations as "port". If this is
  # set to the same value as port, the admin routes will be mounted
  # under /admin.
  adminConnectors:
    - type: http
      port: 8005

# added database connection properties, DatabaseConfiguration
database:
  host: ${WCRS_REGSDB_HOST:-localhost}
  port: ${WCRS_REGSDB_PORT1:-27017}
  name: ${WCRS_REGSDB_NAME:-waste-carriers}
  username: ${WCRS_REGSDB_USERNAME:-mongoUser}
  password: ${WCRS_REGSDB_PASSWORD:-password1234}

# added user database connection properties, DatabaseConfiguration
userDatabase:
  host: ${WCRS_USERSDB_HOST:-localhost}
  port: ${WCRS_USERSDB_PORT1:-27017}
  name: ${WCRS_USERSDB_NAME:-waste-carriers-users}
  username: ${WCRS_USERSDB_USERNAME:-mongoUser}
  password: ${WCRS_USERSDB_PASSWORD:-password1234}

entityMatchingDatabase:
  host: ${WCRS_ENTITY_SEARCH_DB_HOST:-localhost}
  port: ${WCRS_ENTITY_SEARCH_DB_PORT1:-27017}
  name: ${WCRS_ENTITY_SEARCH_DB_NAME:-entity-matching}
  username: ${WCRS_ENTITY_SEARCH_DB_USERNAME:-mongoUser}
  password: ${WCRS_ENTITY_SEARCH_DB_PASSWORD:-password1234}

settings:
  # registration period (in years)
  registrationPeriod: ${WCRS_REGISTRATION_EXPIRES_AFTER:-3}
  # renew period (in months)
  registrationRenewPeriod: ${WCRS_REGISTRATION_RENEWAL_WINDOW:-3}
  # default number of results for search
  searchResultCount: ${WCRS_SERVICE_SEARCH_RESULT_COUNT:-50}

airbrake:
  url: ${WCRS_SERVICES_AIRBRAKE_URL}
  apiKey: ${WCRS_SERVICES_AIRBRAKE_API_KEY}
  environmentName: ${WCRS_SERVICES_AIRBRAKE_ENVNAME}
  # The 'threshold' here can take values: OFF, ERROR, WARN, INFO, DEBUG, TRACE
  # or ALL.  If no value is provided, or the value is unrecognised, by default
  # we only forward messages at ERROR severity.
  threshold: ${WCRS_SERVICES_AIRBRAKE_THRESHOLD:-ERROR}
  # Other values you can set for Airbrake integration, but not required:
  # enabled: true or false (default = true)
  # exceptionsOnly: true or false (default = false)
  
# IrRenewals brings a very limited set of data into Waste Carriers to allow
# IR customers to "renew" in the service.
irRenewals:
  irFolderPath: ${WCRS_SERVICES_IR_RENEWAL_FOLDERPATH:-/srv/java/waste-carriers-service/irdata/}

# Entity matching data allows us to match both the company and people in a
# registration against a list we maintain
entityMatching:
  # Path to the file which contains data on the entities to be matched against
  entitiesFilePath: ${WCRS_SERVICES_ENTITY_SEARCH_FOLDERPATH:-/srv/java/waste-carriers-service/entity_data/entities.csv}
  # The number of characters that must match at the start of a person's first
  # name when matching against people.
  personSearchFirstNameMatchLength: ${WCRS_SERVICES_ENTITY_SEARCH_FN_MATCH_LENGTH:-1}

exportJob:
  # File to use for EPR exports (note: file, not directory).
  eprExportFile: ${WCRS_SERVICES_EPR_EXPORT_FILE:-/srv/java/waste-carriers-service/exports/waste-carriers-epr.csv}
  # Date format to use for EPR exports.
  eprExportDateFormat: "yyyy-MM-dd"
  # Path to use for Reporting Snapshot exports (note: directory, not file).
  reportingExportPath: ${WCRS_SERVICES_REPORTING_EXPORT_PATH:-/srv/java/waste-carriers-service/exports}
  # Date format to use for Reporting Snapshot exports.
  reportingExportDateFormat: "yyyy-MM-dd'T'HH:mm'Z'"
  # Money format to use for Reporting Snapshot exports.
  reportingExportMoneyFormat: "0.00"
  # Cron expression for scheduled job execution.  Leave empty to make the job
  # run on a manual trigger only.  Default is daily at 9pm.
  cronExpression: ${WCRS_SERVICES_EXPORT_JOB_CRON_SCHEDULE:-30 0/15 * * * ?}

registrationStatusJob:
  # Cron expression for scheduled job exectuion.  Leave empty to make the job
  # run on a manual trigger only.  Default is daily at 8pm.
  cronExpression: ${WCRS_SERVICES_STATUS_JOB_CRON_SCHEDULE:-0 0/15 * * * ?}
