#!/bin/bash

# source test_env_vars.sh

export WCRS_SERVICES_REG_HOST_TEST="localhost"
export WCRS_SERVICES_REG_HOST_TEST=27017
export WCRS_SERVICES_REG_NAME_TEST="waste-carriers-test"
export WCRS_SERVICES_REG_USER_TEST="mongoUser"
export WCRS_SERVICES_REG_PASSWD_TEST="password1234"
export WCRS_SERVICES_REG_SERVER_SEL_TIMEOUT_TEST=1000

export WCRS_SERVICES_USR_HOST_TEST="localhost"
export WCRS_SERVICES_USR_PORT_TEST=27017
export WCRS_SERVICES_USR_NAME_TEST="waste-carriers-users-test"
export WCRS_SERVICES_USR_USER_TEST="mongoUser"
export WCRS_SERVICES_USR_PASSWD_TEST="password1234"
export WCRS_SERVICES_USR_SERVER_SEL_TIMEOUT_TEST=1000

export WCRS_SERVICES_EMG_HOST_TEST="localhost"
export WCRS_SERVICES_EMG_PORT_TEST=27017
export WCRS_SERVICES_EMG_NAME_TEST="entity-matching-test"
export WCRS_SERVICES_EMG_USER_TEST="mongoUser"
export WCRS_SERVICES_EMG_PASSWD_TEST="password1234"
export WCRS_SERVICES_EMG_SERVER_SEL_TIMEOUT_TEST=1000
